### ISSUE TITLE
[BUG] dosma.register() throws an error when moving_mask is passed to the function

### ISSUE THREAD

**Issue by barma7** [ad12/DOSMA#116]
**Describe the bug**
dosma.register() throws an error when **_moving_mask_** is passed to the function either as a string or MedicalVolume.

**To Reproduce**

import dosma as dm
from dosma.file_constants as flc

reg_info, reg_vol = dm.register(target, moving, flc.ELASTIX_RIGID_INTERREGISTER_PARAMS_FILE, out_path,
            return_volumes=True,
            target_mask=target_mask_path,
            moving_masks=moving_mask_path,
            rtype=tuple,
            show_pbar=True)

**Expected behavior**
The function is expected to correctly call Elastix using both fixed (target) and moving masks. 

The bug is at line 406 of dosma.register(), and has to do with the fact that we attempt to fill a non existing attribute of the object **reg.inputs**
        
**Code with bug**:
if _use_mask and moving_mask is not None:
     reg.inputs.target_mask = os.path.abspath(moving_mask)

Bug is fixed when naming the correct attribute
**Solution**:
if _use_mask and moving_mask is not None:
     reg.inputs.moving_mask = os.path.abspath(moving_mask)

**Comment by ad12** [comment]
Thanks for the find! Could you make a PR for this?
