### ISSUE TITLE
[BUG] Documentation

### ISSUE THREAD

**Issue by gattia** [ad12/DOSMA#119]
**Describe the bug**
Elastix link for downloading is wrong (seems to have changed). 
- Documentation/Installation/Setup/Registration. (1. Download elastix) <= that points to wrong URL. 

Also, Elastix 5.0.1 gives errors (certain libraries not found) when using clean install of Ubuntu. Elastix 4.9.0 (the same as is used in the `Dosma qMRI Knee Workflow.ipynb`) works out of the box on a clean ubuntu install. Maybe it should be suggested to explicitly recommend that version (4.9.0)?

**Comment by ad12** [comment]
sgtm - could you submit a pull request with these changes? Could you also add the error you were getting with 5.0.1 and the OS you were using. 5.0.1 seems to work fine on linux, but i have not tested on OSX, Windows, or OSX running on the new M1 chip

**Comment by gattia** [comment]
I've made the changes and pull request. My errors were on Ubuntu 18.04 - which I think I saw after making this post was the version of Ubuntu used in the colab notebooks and is why those notebooks also used 4.9.0. 

In the next week or so I'll have an intel and M1 mac - I can try try running on both and provide recommendations as appropriate.
