### ISSUE TITLE
Convert Left/Right orientation to Medial/Lateral for knee

### ISSUE THREAD

**Issue by ad12** [ad12/DOSMA#32]
Current coordinate systems save information in terms of `left` and `right`. However, for knee analysis in particular, determining if `left` corresponds to the `medial` or `lateral` condyle (side).

**Comment by ad12** [comment]
this can be added as a module in the future, but is out of scope at the moment. feel free to reopen at a later time

**Comment by gattia** [comment]
This seems like a really good idea to me. I know I've had the same problem a fair amount. 

If the leg (right/left) were documented in the MedicalVolume then the Med/Lat orientation could easily be identified.
